const express = require('express')

const workspaceRoutes = require('./workspace.route')
const manufacturerRoutes = require('./manufacturer.route')
const itemRoutes = require('./item.route')
const orderRoutes = require('./order.route')
const customerRoutes = require('./customer.route')
const employeeRoutes = require('./employee.route')
const roleRoutes = require('./role.route')
const paymentRoutes = require('./payment.route')
const statusRoutes = require('./status.route')
const currencyRoutes = require('./currency.route')
const authRoutes = require('./auth.route')
const userRoutes = require('./user.route')

const router = express.Router()

router.use('/workspace', workspaceRoutes)
router.use('/manufacturer', manufacturerRoutes)
router.use('/customer', customerRoutes)
router.use('/employee', employeeRoutes)
router.use('/item', itemRoutes)
router.use('/order', orderRoutes)
router.use('/role', roleRoutes)
router.use('/payment', paymentRoutes)
router.use('/status', statusRoutes)
router.use('/currency', currencyRoutes)
router.use('/auth', authRoutes)
router.use('/user', userRoutes)

module.exports = router
